<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>PortManager.Desktop</AssemblyName>
		<ApplicationIcon>appicon.ico</ApplicationIcon>
		<AssemblyTitle>端口管理器桌面版</AssemblyTitle>
		<Description>PortManager 桌面版，功能强大的端口管理工具</Description>
		<Company>科控物联</Company>
		<Copyright>©2024-2026 科控物联</Copyright>
		<VersionPrefix>3.1</VersionPrefix>
		<VersionSuffix>$([System.DateTime]::Now.ToString(`yyyy.MMdd`))</VersionSuffix>
		<Version>$(VersionPrefix).$(VersionSuffix)</Version>
		<FileVersion>$(Version)</FileVersion>
		<AssemblyVersion>$(VersionPrefix).*</AssemblyVersion>
		<Deterministic>false</Deterministic>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Masa.Blazor" Version="1.11.9" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="10.0.41" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
		<PackageReference Include="System.Management" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PortManager.Core\PortManager.Core.csproj" />
		<ProjectReference Include="..\PortManager.Shared\PortManager.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Update="appicon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
